post http://localhost:5000/signup 

Content-Type: application/json
{
    "email": "test1@gmail.com"
}



###
post http://localhost:5000/payment/create-setup-intent

{
    "email": "test@gmail.com"
}

###

post http://localhost:5000/payment/paymentUpdate

{
    "email": "test@gmail.com",
    "paymentMethodId": "pm_1GXz7xlZxY5Fcq9Z2p5QZQw",

}